### PR TITLE
Updated Precision Piezo values

### PR DESCRIPTION
**Pull request by xepherys**
Updated for Orion v1.2 (current as of 2019-05-20) and Orion v2.0 (currently in testing) digital and analog setups. Note on setting p-val for analog setup.

### CODE REVIEW

**Review by JohnOCFII — COMMENTED** [review]
Can you explain the desire to change the G31 P and R values?  Mine are close to, but a little different from the current examples.

**Comment by dandancheeseandham** [comment]
In the comments it says "Your p-val is going to depend a lot on your particular setup.  Look at the z-probe resting value and add 10-20."
I don't have a Piezo, but it's good that someone looks at that probes values, so anyone with it please do chime in.

**Comment by xepherys** [comment]
@JohnOFCII - The G31 P value doesn’t really matter, so far as I can tell, for the digital board (v1.2) since it’s either triggered or not triggered. That was a copy/paste of my Orion section. In the event that I’m incorrect, and the digital response is something other than 0 or 1000, 50 would be a more accurate value. I guess technically 1 would be ideal in that case.

The R value for the M558 obviously does matter with digital, but could probably be left at the default value of 0. I set it to 0.5 as an over-abundance of caution, but there isn’t really a recovery period of any note. Even when I’ve had it probe/pop/probe I’ve had it set to 0.1 successfully, and actually use 0.1 for the v2 board in either analog or digital mode.

**Comment by xepherys** [comment]
Dan - it may be worth writing up a small section on setting up with a piezo in either analog or digital format.  It's not complicated, by any means, but there are some points that aren't quite the same as setting up with BL-t or iR.  The p-val for analog depends on the resting value (which is determined by any adjustments to the potentiometer, how tightly the board is sandwiched into the tool, and the boards position in the tool), how static it's resting value is (which can depend on the above as well as mechanical properties unique to each build even with identical parts), and the physics of your z-probe in action (all of the above plus speed of probe and the like).

My OrionV2 is quite stable at rest and during z-movements, and I personally use a value that is typically 5 points above stable.  10pt is entirely serviceable, still very sensitive, and gives a little leeway.  Idris uses 15-20 and he made the thing, but his hardware is different and it sounds like he doesn't have as stable a value during z-movements (thanks ZL!).

In the end it's incredibly easy to set up and dial in, but everyone's values are likely to be very different.  At a minimum, even sticking to 10-20, the actual numeric value is almost certain to be different between any two machines, even if only by a few points.

**Comment by lostapathy** [comment]
@xepherys please do contribute such a doc!  neither @dandancheeseandham nor I have a piezo so hard for us to contribute that.

**Comment by xepherys** [comment]
@lostapathy - I will put that on my to-do list and move it toward the top.  Just need to get my second printer up and running with a new tool carriage and get a few things worked out on the RailCore.

**Pull request merged**
