### PR TITLE
Fast bed levelling & mesh report.

### PR DESCRIPTION
**Pull request by dandancheeseandham**
I think this is ready for testing. It only adds files, it is a macro and there are no permanent changes to your system are performed.

Any volunteers? 😈 

## Support files for macro "0_Fast_Truelevel_with_Mesh.g"

**Effect:** Homes, performs 3 bed-levelling routines and probes the bed for information (mesh comp. disabled afterwards)
**Use-case:** Time-saving macro, in order to get the bed as level as possible and then measured to check rail alignment. My typical level & probe time is 1min 20secs.

To use "0_Fast_Truelevel_with_Mesh.g" you **must**:-

1. Create a "bed-nodrop.g" in your sys directory. Just copy your bed.g file contents, remove any G1 Z moves (to save time raising Z up more and probing down.)
1. Alter the H height on the "3) Home Z" line to at least 1mm more than your typical probe height.
1. (Optional) Create an optimised home X and Y script (homexy-nodrop.g) in one file in sys.(examples are in "\sys\config-user examples\fast_truelevel_with_mesh") Again, remove all Z raises or drops, to replace "G28 X Y" line at the start with the M98 calling this file.

### Removal

Remove macro "0_Fast_Truelevel_with_Mesh.g"
Remove file /sys/bed-nodrop.g
Remove file /sys/homexy-nodrop.g

### CODE REVIEW

**Comment by dandancheeseandham** [comment]
Demo: https://photos.app.goo.gl/2LEsfMfBp8YtE9ok6

**Comment by EmmaPuggle** [comment]
I can do a test run later today. Is the current consensus that 3 point leveling is the stock method vs 4 point?

**Comment by dandancheeseandham** [comment]
@EmmaPuggle thanks!

I believe that 3 point is enough, as that defines a plane. 4 point is used by the BL-touch people with a mag-bed (which are a growing number) I assume it is to avoid magnets near the right hand yoke.

4 point is OK though if you want to use it, it doesn't hurt.

**Comment by EmmaPuggle** [comment]
@dandancheeseandham 

My latest mental framework is that 3 point is a bit of a misdirection as it isn't showing you the true flatness - hence always resolving from 0.nnn to a perfect 0.000, whereas the 4 point is a 'true' flatness. Visually I think of it as you can't use a single triangle to define a square (well a single triangle anyway? I failed all my maths since I was 15). Wish I had a source on that but I ran out of steam trying to collect and track the source of everything. Could search discord but lolz how much do you hate yourself...

But I'm not confident in that truth to make it default.

**Comment by kraegar** [comment]
I use 4 point for quick routine validation of how parallel my X rails are.
3 point doesn't show X rail skew.  I've left it as the default so far,
though.

**Comment by dandancheeseandham** [comment]
No worries, I certainly need to learn more too.
This is why I didn't provide a bed.g (except as an example) and copy your own, as different people have their choices and bed coordinates.

I've created a "Quieter_TrueLevel_and_Probe.g" which moves a bit more sedately on X & Y, is quieter and adds 30 seconds to the total time (basically the same file, but with speeds on XY halved). It'll be interesting to see if people have a preference.

**Comment by dandancheeseandham** [comment]
Closed. I'm working on a better method :)

**Pull request closed without merging**
