### PR TITLE
issue #24 - Add auto tuning

### PR DESCRIPTION
**Pull request by dandancheeseandham**
I feel more discussion is necessary before this is approved. Mostly some agreement on whether there should be a generic heater model within config.g or not.
Testing on a Railcore would be a nice addition, but probably is not absolutely necessary.

Patch notes:

 * Remove default heater model for heater 1.
 * add auto tuning macros
 * add M501 to config.g to run config-override.g

### CODE REVIEW

**Comment by dandancheeseandham** [comment]
Previous discussion in https://github.com/railcore/configs/issues/24

**Comment by dandancheeseandham** [comment]
IRC log

(JohnOCFII) cheeseandham - either I'm doing it wrong, or the macro is not behaving.
(JohnOCFII) When I launch the macro, it writes out M500 to update the config-overide BEFORE actually completing the test.
(JohnOCFII) I f I wait, I can then do the M307 to show results or again do the M500, and it then does put fresh values in the config-override file
(cheeseandham) that is odd, it seemed to work with spaces and writing to config-override.g with me - although I am on  FW 2.03beta1

(cheeseandham) I've just renamed my config-override and running the macro
(cheeseandham) 19:59:33M98 P"0:/macros/tuning/Heater tuning/Tune Tool 0"
(cheeseandham) Auto tuning heater 1 using target temperature 260.0°C and PWM 1.00 - do not leave printer unattended
(cheeseandham) JohnOCFII, I doubt you're doing it wrong :) but there is something odd going on
(cheeseandham) and it's probably Duet :)
(cheeseandham) JohnOCFII, FYI, worked here with spaces and to be sure I renamed my confi-override.g to double-check it was generating a new one (I'd only checked the last modify date before) https://imgur.com/a/CHqJbV2
(cheeseandham) but it's good you've checked, if it's not reliable then we can't use it

**Comment by JohnOCFII** [comment]
Thanks.  I should have just commented here.

**Comment by lostapathy** [comment]
This conflicts with the naming conventions of https://github.com/railcore/configs/tree/master/duet#macros - I don't really mind if we want to update the conventions, but we should get them in sync

**Comment by dandancheeseandham** [comment]
@lostapathy  heh, well spotted. 

No, I simply forgot :smile:

**Pull request closed without merging**
