### PR TITLE
Probes

### PR DESCRIPTION
**Pull request by dandancheeseandham**

### CODE REVIEW

**Comment by natewalck** [comment]
Perhaps it would be better to have *no* probes enabled by default. Home Z would fail if no probes were defined, correct? This would force people to at *least* uncomment the probe line of their choosing and hopefully read the comments

**Comment by JohnOCFII** [comment]
I like Nate's idea.  It will force people to realize they need to do work before they launch into something that could be detrimental.

**Comment by dandancheeseandham** [comment]
I'm down with that, but then perhaps we should somehow disable homez.g too?

**Comment by dandancheeseandham** [comment]
Oh wait, just reread, does homez.g fail if no probes are enabled? If so, cool.

**Comment by dandancheeseandham** [comment]
OK.

Moved deployprobe.g and retractprobe.g out of sys, this was due to a warning on https://duet3d.dozuki.com/Wiki/Macros  that I noticed
**"Note: If you do not have a Z probe that needs to deploy or retract you must not have these files in the /sys/ directory"**

Removed "probe-" prefix as they are already in a probe directory.

Renamed "zprobes" to "zprobe" - while there are several in there, only one is activated at any one time.

Commented out the IR probe line, so no probes are enabled by default as suggested above.

**Pull request merged**
