### PR TITLE
Create RailCore_300ZL_Config_JO.ini

### PR DESCRIPTION
**Pull request by JohnOCFII**
My Slic3r PE config for my RailCore 300ZL.  This config uses my versions of the Duet bed.g, config.g and homeall.g files.  Please review my start code and compare with your Duet RRF files before using.

### CODE REVIEW

**Comment by lostapathy** [comment]
Are you doing anything particularly exotic with your g-code config files that this requires, or are they fairly normal?  If so, we should probably describe what, and we probably should come up with a way to organize the repo to keep the slicer and machines together.

**Comment by JohnOCFII** [comment]
I don't believe I'm doing anything exotic in my g-code configs files, but since I'm calling G28 to home all axes and G32 for the bed tramming, I wanted to make sure folks had a chance to review, as I've learned not everyone does things the same way.

I'm certainly open to a different organization.  Not sure what would make the most sense.  My S3D start code has similar calls.

**Comment by natewalck** [comment]
As discussed on #railcore, add a README.md that calls out the G28/G32 behavior in the slicer config so its more obvious to casual onlookers.

**Comment by lostapathy** [comment]
Should we maybe put the slicer config, README, and your homing config files in one directory all together, then?  That way they are all readily at hand together and it's clear that the config files are just contextual reference for the slicer config, and not some sort of alternate configuration.

**Comment by natewalck** [comment]
Slicer configs and duet/klipper configs are separate items that are not *really* connected. I could use this slic3r config with my own bed.g and config.g and it would work perfectly. A G28 is a G28 and a G32 is a G32, so I think noting it in the readme for the slic3r config makes sense. The user can always grab the slic3r config and remove those  from the pre-run gcode.

**Pull request merged**
